5 visualização de filmes em exibição
Imeguras/AInet_2022 pull request #25
Opened 2022-06-07 16:19 UTC by Kibo1999

Acho que agora acabei o issue.

2022-06-09 12:54 UTC, Imeguras requested changes
TL;DR: falta aqui só basicamente deixares que uma sessão esteja esgotada mas apareça nas sessões

2022-06-09 12:54 UTC, Imeguras commented on app/Http/Controllers/FilmesController.php
> +        $sessoes = Sessao::withCount('lugares')->withCount('bilhetes')->where('filme_id', $filme->id)->where('data', '>=', date("Y-m-d"))->havingRaw('bilhetes_count < lugares_count')->get();
mmmm e o que acontece se estiver estiver esgotado ie bilhetes_count== lugares_count
o stor pediu que se tivesse esgotado o utilizador tem de poder inferir que já está esgotado e que por isso não consegue mais ir "algo que
indique se a sessão está esgotada ou não."
---
Also isto e irrelevante mas se tiveres as 23:59 da noite vai dar para poder ver e escolher sessoes que ja nao existem(de qualquer maneira o stor nao especifica como deve ser o comportamento quanto as horas por isso ta tudo bem acho eu)

2022-06-09 12:54 UTC, Imeguras commented on app/Models/Sessao.php
> +        return $this->hasManyThrough(Lugar::class, Sala::class,
clueless? isto não devia ser review mas então duas salas podem ter o mesmo lugar?

2022-06-09 13:25 UTC, Imeguras approved these changes
Parece estar bom

2022-06-09 13:25 UTC, Imeguras commented on app/Http/Controllers/FilmesController.php
> +            $query->where('data', '>', date("Y-m-d"));
all is well

2022-06-09 13:25 UTC, Imeguras commented on resources/views/filmes/index.blade.php
> +								 		<iframe  src="https://www.youtube.com/embed/{{ substr($filme->trailer_url, 32) }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-m
tenho ideia que já mudaste, mas fazer clip de strings hardcoded é má ideia especialmente com o youtube já que a cada dois dias eles mudam o código do url, etc..., para quebrar "downloads". De qualquer maneira acho que se fores ao codigo já fiz cenas mais aggregious e como disse antes ja deve estar mudado

2022-06-09 13:25 UTC, Imeguras commented on resources/views/filmes/index.blade.php
> +<script type="text/javascript">
acho que dava para fazer isto com classes(ie para quê usar javascript quando podes usar css) mas whatever, acho que o stor tambem gosta de javascript also se tás a perguntar "eu ja mudei isso" tipo isto e por commit e eu fui conas, e começei de tras para a frente e agoora mudei

2022-06-09 13:25 UTC, Imeguras commented on resources/views/welcome.blade.php
> +        <title>CineMagic</title>
Cuidado isto permite fazer XSS, kek tou a gozar

2022-06-09 13:28 UTC, Imeguras requested changes
Eu dei review de outra cena mas pensava que isto era por commit aparentemente e para tudo

2022-06-13 07:48 UTC, Kibo1999 commented on resources/views/filmes/comprar.blade.php
> +							    		<td><a href= "#" class="btn btn-primary justify-content-right">Escolher Sessão</a></td>
exato, eles podem adicionar ao carrinho, só não podem depois exercer o comprar, já alterei isso.

2022-06-13 07:49 UTC, Kibo1999 commented on resources/views/filmes/comprar.blade.php
> +							    	<td>{{$sessao->lugares_count - $sessao->bilhetes_count}}</td>
o count dos lugares já tem em atenção se um lugar foi deleted ou não, mesmo sendo só soft deleted.

2022-06-13 07:50 UTC, Kibo1999 commented on app/Models/Sessao.php
> +        return $this->hasManyThrough(Lugar::class, Sala::class,
O "hasManyThrough()" é só para saber quantos lugares existem na sala em que a sessão vai decorrer.

2022-06-13 07:51 UTC, Kibo1999 commented on app/Http/Controllers/FilmesController.php
> +        $sessoes = Sessao::withCount('lugares')->withCount('bilhetes')->where('filme_id', $filme->id)->where('data', '>=', date("Y-m-d"))->havingRaw('bilhetes_count < lugares_count')->get();
A parte da hora, já a corrigi.
Se bilhetes_count == lugares_count, ele não vai mostrar, ou, se mostrar, ele diz que não tem lugares disponiveis.

2022-06-13 07:52 UTC, Kibo1999 commented on app/Http/Controllers/FilmesController.php
> +        $sessoes = Sessao::withCount('lugares')->withCount('bilhetes')->where('filme_id', $filme->id)->where('data', '>=', date("Y-m-d"))->havingRaw('bilhetes_count < lugares_count')->get();
desculpa, como está feita a query, se bilhetes_count == lugares_count, ele não vai buscar essa sessão.

2022-06-13 08:14 UTC, merged